SEED = 1
EPOCHS = 1
BATCH_SIZE = 4
WEIGHT_DECAY = 0
AUGMENT_RATE_DOT = 0.15
AUGMENT_RATE_COMMA = 0.15
LEARNING_RATE = 5e-6
NUMBER_USED_CPU_CORES = 8
DATASET_DATA_KEYS = [['passage', 'text'], ['text'], ['document'], ['article'], ['passage'], ['source']]
DATASET_DEFAULT_EXTENSION = 'txt'
DATASET_NORMALIZED_EXTENSION = f'normalized'
DATASET_PARSE_EXTENSIONS = ['json', 'jsonl', 'csv']
